"""expand creative title to text

Revision ID: 7e3e1ac3ff91
Revises: ff75bde9c0a8
Create Date: 2026-06-05 03:21:04.714252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e3e1ac3ff91'
down_revision: Union[str, None] = 'ff75bde9c0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creatives', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creatives', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
