"""initial_schema

Revision ID: 8e583ed5374b
Revises: 
Create Date: 2026-05-30 19:10:32.945371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8e583ed5374b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_action_stats',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'date', 'field_name', 'action_type', name='uq_action_stats_entity_date_field_action')
    )
    op.create_index('ix_action_stats_account_date_field_action', 'metric_action_stats', ['account_id', 'date', 'field_name', 'action_type'], unique=False)
    op.create_index('ix_action_stats_entity_date', 'metric_action_stats', ['entity_id', 'date'], unique=False)
    op.create_table('metric_breakdowns',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('breakdown_type', sa.String(length=50), nullable=False),
    sa.Column('breakdown_value', sa.String(length=200), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'date', 'breakdown_type', 'breakdown_value', name='uq_breakdowns_entity_date_type_value')
    )
    op.create_index('ix_breakdowns_account_date', 'metric_breakdowns', ['account_id', 'date'], unique=False)
    op.create_index('ix_breakdowns_entity_date', 'metric_breakdowns', ['entity_id', 'date'], unique=False)
    op.create_table('metrics_daily',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('reach', sa.BigInteger(), nullable=True),
    sa.Column('frequency', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('cpp', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unique_clicks', sa.BigInteger(), nullable=True),
    sa.Column('inline_link_clicks', sa.BigInteger(), nullable=True),
    sa.Column('unique_inline_link_clicks', sa.BigInteger(), nullable=True),
    sa.Column('inline_link_click_ctr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('unique_ctr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cost_per_inline_link_click', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('cost_per_unique_click', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('inline_post_engagement', sa.BigInteger(), nullable=True),
    sa.Column('cost_per_inline_post_engagement', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('auction_bid', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('auction_competitiveness', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('auction_max_competitor_bid', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('total_actions', sa.BigInteger(), nullable=True),
    sa.Column('total_unique_actions', sa.BigInteger(), nullable=True),
    sa.Column('result_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('estimated_ad_recall_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('estimated_ad_recallers', sa.BigInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('attribution_window', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'date', name='uq_metrics_daily_entity_date')
    )
    op.create_index('ix_metrics_daily_account_date', 'metrics_daily', ['account_id', 'date'], unique=False)
    op.create_index('ix_metrics_daily_account_entity_type', 'metrics_daily', ['account_id', 'entity_type'], unique=False)
    op.create_index('ix_metrics_daily_entity_date', 'metrics_daily', ['entity_id', 'date'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_organizations_slug')
    )
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency_field', sa.String(length=100), nullable=True),
    sa.Column('timezone_field', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_verify_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('invite_token', sa.String(length=255), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name='ck_membership_role'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership_org_user')
    )
    op.create_index('ix_membership_invite_token', 'organization_memberships', ['invite_token'], unique=False)
    op.create_index('ix_membership_org_id', 'organization_memberships', ['organization_id'], unique=False)
    op.create_index('ix_membership_user_id', 'organization_memberships', ['user_id'], unique=False)
    op.create_table('platform_connections',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('connected_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connections_org_id', 'platform_connections', ['organization_id'], unique=False)
    op.create_index('ix_connections_platform_id', 'platform_connections', ['platform_id'], unique=False)
    op.create_table('accounts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('platform_connection_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('account_status', sa.String(length=50), nullable=False),
    sa.Column('business_id', sa.String(length=100), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'platform_id', 'external_id', name='uq_account_org_platform_external')
    )
    op.create_index('ix_accounts_org_id', 'accounts', ['organization_id'], unique=False)
    op.create_index('ix_accounts_platform_connection_id', 'accounts', ['platform_connection_id'], unique=False)
    op.create_table('account_configs',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('primary_conversion_action', sa.String(length=100), nullable=True),
    sa.Column('attribution_window', sa.String(length=50), nullable=True),
    sa.Column('roas_action_type', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_account_config_account')
    )
    op.create_table('campaigns',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('platform_campaign_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('effective_status', sa.String(length=50), nullable=False),
    sa.Column('objective', sa.String(length=50), nullable=True),
    sa.Column('platform_objective', sa.String(length=100), nullable=True),
    sa.Column('daily_budget', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('lifetime_budget', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('buying_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'platform_campaign_id', name='uq_campaign_account_platform_id')
    )
    op.create_index('ix_campaigns_account_id', 'campaigns', ['account_id'], unique=False)
    op.create_index('ix_campaigns_platform_id', 'campaigns', ['platform_id'], unique=False)
    op.create_index('ix_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_table('creatives',
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('platform_creative_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.String(length=5000), nullable=True),
    sa.Column('image_url', sa.String(length=2000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2000), nullable=True),
    sa.Column('video_id', sa.String(length=100), nullable=True),
    sa.Column('cta_type', sa.String(length=50), nullable=True),
    sa.Column('destination_url', sa.String(length=2000), nullable=True),
    sa.Column('raw_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'platform_creative_id', name='uq_creative_account_platform_id')
    )
    op.create_index('ix_creatives_account_id', 'creatives', ['account_id'], unique=False)
    op.create_index('ix_creatives_platform_creative_id', 'creatives', ['platform_creative_id'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_stop', sa.Date(), nullable=True),
    sa.Column('breakdown_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('platform_job_id', sa.String(length=100), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rate_limit_pct_at_start', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_jobs_account_type_status', 'sync_jobs', ['account_id', 'job_type', 'status'], unique=False)
    op.create_index('ix_sync_jobs_created_at', 'sync_jobs', ['created_at'], unique=False)
    op.create_index('ix_sync_jobs_type_status_platform_job', 'sync_jobs', ['job_type', 'status', 'platform_job_id'], unique=False)
    op.create_table('ad_groups',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('platform_adgroup_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('effective_status', sa.String(length=50), nullable=False),
    sa.Column('optimization_goal', sa.String(length=100), nullable=True),
    sa.Column('billing_event', sa.String(length=50), nullable=True),
    sa.Column('bid_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('daily_budget', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('lifetime_budget', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('targeting_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'platform_adgroup_id', name='uq_adgroup_account_platform_id')
    )
    op.create_index('ix_adgroups_account_id', 'ad_groups', ['account_id'], unique=False)
    op.create_index('ix_adgroups_campaign_id', 'ad_groups', ['campaign_id'], unique=False)
    op.create_index('ix_adgroups_status', 'ad_groups', ['status'], unique=False)
    op.create_table('ads',
    sa.Column('ad_group_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('platform_ad_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('effective_status', sa.String(length=50), nullable=False),
    sa.Column('creative_id', sa.Uuid(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'platform_ad_id', name='uq_ad_account_platform_id')
    )
    op.create_index('ix_ads_account_id', 'ads', ['account_id'], unique=False)
    op.create_index('ix_ads_ad_group_id', 'ads', ['ad_group_id'], unique=False)
    op.create_index('ix_ads_campaign_id', 'ads', ['campaign_id'], unique=False)
    op.create_index('ix_ads_status', 'ads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ads_status', table_name='ads')
    op.drop_index('ix_ads_campaign_id', table_name='ads')
    op.drop_index('ix_ads_ad_group_id', table_name='ads')
    op.drop_index('ix_ads_account_id', table_name='ads')
    op.drop_table('ads')
    op.drop_index('ix_adgroups_status', table_name='ad_groups')
    op.drop_index('ix_adgroups_campaign_id', table_name='ad_groups')
    op.drop_index('ix_adgroups_account_id', table_name='ad_groups')
    op.drop_table('ad_groups')
    op.drop_index('ix_sync_jobs_type_status_platform_job', table_name='sync_jobs')
    op.drop_index('ix_sync_jobs_created_at', table_name='sync_jobs')
    op.drop_index('ix_sync_jobs_account_type_status', table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index('ix_creatives_platform_creative_id', table_name='creatives')
    op.drop_index('ix_creatives_account_id', table_name='creatives')
    op.drop_table('creatives')
    op.drop_index('ix_campaigns_status', table_name='campaigns')
    op.drop_index('ix_campaigns_platform_id', table_name='campaigns')
    op.drop_index('ix_campaigns_account_id', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('account_configs')
    op.drop_index('ix_accounts_platform_connection_id', table_name='accounts')
    op.drop_index('ix_accounts_org_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_connections_platform_id', table_name='platform_connections')
    op.drop_index('ix_connections_org_id', table_name='platform_connections')
    op.drop_table('platform_connections')
    op.drop_index('ix_membership_user_id', table_name='organization_memberships')
    op.drop_index('ix_membership_org_id', table_name='organization_memberships')
    op.drop_index('ix_membership_invite_token', table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('platforms')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_metrics_daily_entity_date', table_name='metrics_daily')
    op.drop_index('ix_metrics_daily_account_entity_type', table_name='metrics_daily')
    op.drop_index('ix_metrics_daily_account_date', table_name='metrics_daily')
    op.drop_table('metrics_daily')
    op.drop_index('ix_breakdowns_entity_date', table_name='metric_breakdowns')
    op.drop_index('ix_breakdowns_account_date', table_name='metric_breakdowns')
    op.drop_table('metric_breakdowns')
    op.drop_index('ix_action_stats_entity_date', table_name='metric_action_stats')
    op.drop_index('ix_action_stats_account_date_field_action', table_name='metric_action_stats')
    op.drop_table('metric_action_stats')
    # ### end Alembic commands ###
