"""add reach+conversions to metric_breakdowns

Revision ID: f05a9fcb7e8d
Revises: 7e3e1ac3ff91
Create Date: 2026-06-05 16:10:53.515525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f05a9fcb7e8d'
down_revision: Union[str, None] = '7e3e1ac3ff91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_breakdowns', sa.Column('reach', sa.BigInteger(), nullable=True))
    op.add_column('metric_breakdowns', sa.Column('conversions', sa.Numeric(precision=18, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric_breakdowns', 'conversions')
    op.drop_column('metric_breakdowns', 'reach')
    # ### end Alembic commands ###
