"""add account_type to accounts

Revision ID: ff75bde9c0a8
Revises: a1b2c3d4e5f6
Create Date: 2026-06-03 16:07:56.669224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff75bde9c0a8'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_type', sa.String(length=20), server_default='standard', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_type')
    # ### end Alembic commands ###
