"""Seed platforms reference table

Revision ID: seed_platforms_001
Revises:
Create Date: 2026-05-30

NOTE: Run this AFTER initial_schema migration.
Update 'down_revision' to match the revision ID generated by
`alembic revision --autogenerate -m "initial_schema"`.
"""
from alembic import op
import sqlalchemy as sa

revision = "seed_platforms_001"
down_revision = "8e583ed5374b"
branch_labels = None
depends_on = None

PLATFORMS = [
    {
        "id": "meta",
        "name": "Meta Ads",
        "currency_field": "account_currency",
        "timezone_field": "timezone_name",
    },
    {
        "id": "google_ads",
        "name": "Google Ads",
        "currency_field": "currency_code",
        "timezone_field": "time_zone",
    },
    {
        "id": "tiktok",
        "name": "TikTok Ads",
        "currency_field": "currency",
        "timezone_field": "timezone",
    },
    {
        "id": "google_analytics",
        "name": "Google Analytics 4",
        "currency_field": None,
        "timezone_field": "timezone",
    },
]


def upgrade() -> None:
    platforms_table = sa.table(
        "platforms",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("currency_field", sa.String),
        sa.column("timezone_field", sa.String),
    )
    op.bulk_insert(platforms_table, PLATFORMS)


def downgrade() -> None:
    op.execute("DELETE FROM platforms WHERE id IN ('meta', 'google_ads', 'tiktok', 'google_analytics')")
